### ISSUE TITLE
demo: `undefined: platformUSBIPExec` on Linux 

### ISSUE THREAD

**Issue by stefan2904** [bulwarkid/virtual-fido#20]
I cannot run the demo (on the latest master, commit 2ebf6ee061431aa401217e168447a80725e12383) on Ubuntu 22.04.2.

Maybe I am missing something, but when I run `sudo go run ./cmd/demo start` I get:

```bash
# github.com/bulwarkid/virtual-fido/cmd/demo
cmd/demo/server.go:83:11: undefined: platformUSBIPExec
```

Looks like `platformUSBIPExec` is only implemented in `exec_windows.go`?

**Comment by cmdli** [comment]
Interesting; that should be implemented in `exec_linux.go`. Let me take a look. Thanks for the report!

**Comment by cmdli** [comment]
Alright, this should be fixed with https://github.com/bulwarkid/virtual-fido/commit/7bab84576767a28e5edfea82b68b4ee8ac0ccaae. Looks like a bad .gitignore caused new files in `cmd/demo` to be ignored, which included the (now added) `exec_linux.go` and `exec_macos.go`. Thanks for reporting this; I probably wouldn't have caught it on my machine since the files are there, just not tracked by git.
