### ISSUE TITLE
how faithful it is

### ISSUE THREAD

**Issue by ibnuda** [bulwarkid/virtual-fido#7]
sorry for the dumb title, and it is NOT an issue, just some questions.
what i want to ask is, how faithful it is to the fido protocol?
and compared to hardware impl., say, yubikey, is the inner working of this implementation about the same?
thanks.

**Comment by cmdli** [comment]
Sorry for the late response. This should be a full implementation of the FIDO2 and U2F protocols, though some optional features may not be used (for instance, attestation is only done using self-attestation). There might be bugs with it as of now since it's just in beta, but otherwise it should be complete enough to work for WebAuthN or 2FA.
